const score = 400;
//console.log(score);

const balance = new Number(100);
//console.log(balance);

//console.log(balance.toString().length);
//console.log(balance.toFixed(1));

const otherNumber = 12345.515151;
//console.log(otherNumber.toPrecision(5));

const otherNumber2 = [1,2,3,4,5,6,7,8,9,0];
//console.log(otherNumber2.maxvalue());

const num = 1000000;
//console.log(num.toLocaleString('es-IN'));

//============== Maths ==============

//console.log(Math);
//console.log(Math.abs(-5));
//console.log(Math.ceil(5.1));
//console.log(Math.floor(5.9));
//console.log(Math.round(5.5));
//console.log(Math.sqrt(64));
//console.log(Math.pow(4, 3));
//console.log(Math.min(1,2,3,4,5,6,7,8,9,0));
//console.log(Math.max(1,2,3,4,5,6,7,8,9,0));

//console.log((Math.random() * 10) + 1);
//console.log((Math.random() * 10) + 1);
//console.log(Math.floor(Math.random() * 15) + 1);

const min = 10;
const max = 20;

//console.log(Math.floor(Math.random() * (max - min + 1)))


